Appcreche/routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Creches
    Route::delete('creches/destroy', 'CrechesController@massDestroy')->name('creches.massDestroy');
    Route::resource('creches', 'CrechesController');

    // Bebes
    Route::delete('bebes/destroy', 'BebesController@massDestroy')->name('bebes.massDestroy');
    Route::resource('bebes', 'BebesController');

    // Informations_supplementaires
    Route::delete('informations_supplementaires/destroy', 'Informations_supplementairesController@massDestroy')->name('informations_supplementaires.massDestroy');
    Route::resource('informations_supplementaires', 'Informations_supplementairesController');
});

Appcreche/app/Bebe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bebe extends Model
{
    protected $table = 'bebe';

    protected $fillable = array('nom', 'prenom', 'date_naissance', 'sexe', 'nationalite', 'creche_id');

    public static $rules = array('nom'=>'nullable|min=1',
                                 'prenom'=>'nullable|min=1',
                                 'date_naissance'=>'numeric',
                                 'sexe'=>'nullable|min=1',
                                 'nationalite'=>'nullable',
                                 'creche_id'=>'nullable|integer'    
                                );


    public function creche()
    {
        return $this->belongsTo(Creche::class, 'creche_id');
    }

    public function parents()
    {
        return $this->belongsToMany('Parents');
    }

    public function journee_bebe()
    {
        return $this->hasMany('Journee_Bebe');
    }

    public function informations_supplementaires()
    {
        return $this->hasOne('Informations_Supplementaires');
    }

    public function prestation()
    {
        return $this->belongsToMany('Prestation');
    }

    public function sante()
    {
        return $this->hasOne('Sante');
    }

    public function facturation()
    {
        return $this->hasManyThrough('Facturation');
    }
}

Appcreche/app/Http/Controllers/Admin/BebesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreBebeRequest;
use App\Http\Requests\UpdateBebeRequest;
use App\Http\Requests\MassDestroyBebeRequest;


use Gate;
use Auth;
use App\Bebe;
use App\Creche;
use App\User;
use App\Role;
use Symfony\Component\HttpFoundation\Response;
 
class BebesController extends Controller
{
    public function index()
    {
        
        $user = Auth::user();
        $user->load('creches');

        if ($user->roles()->where('title', 'admin')->exists()) {
            $bebes = Bebe::whereHas('creche', function($query) use ($user) { 
                $query->where('nom', $user->creches->first()->nom); 
            })->get();
        } else {
            $bebes = Bebe::all();
        } 
           
        return view('admin.bebes.index', compact('bebes','user'));
    }

    public function create()
    {
        abort_if(Gate::denies('user_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $user = Auth::user();

        if ($user->roles()->where('title', 'admin')->exists()) {
            $creches = Creche::where('nom', $user->creches->first()->nom)->pluck('nom', 'id');
        } else {
            $creches = Creche::all()->pluck('nom', 'id');
        } 

        return view('admin.bebes.create', compact('creches'));
    }

    public function store(StoreBebeRequest $request)
    {
        $bebe = Bebe::create($request->all());

        return redirect()->route('admin.bebes.index');
    }

    public function edit(Bebe $bebe)
    {
        $user = Auth::user();

        if ($user->roles()->where('title', 'admin')->exists()) {
            $creches = Creche::where('nom', $user->creches->first()->nom)->pluck('nom', 'id');
        } else {
            $creches = Creche::all()->pluck('nom', 'id');
        } 
 
        return view('admin.bebes.edit', compact('bebe','creches'));
    }

    public function update(UpdateBebeRequest $request, Bebe $bebe)
    {
        $bebe->update($request->all());

        return redirect()->route('admin.bebes.index');
    }

    public function show(Bebe $bebe)
    {
        return view('admin.bebes.show', compact('bebe'));
    }

    public function destroy(Bebe $bebe)
    {
        ('bebe_delete');

        $bebe->delete();

        return back();
    }

    public function massDestroy(MassDestroyBebeRequest $request)
    {
        Bebe::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

Appcreche/resources/views/admin/bebes/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('bébé') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.bebes.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="nom">{{ trans('Nom ') }}</label>
                <input class="form-control {{ $errors->has('nom') ? 'is-invalid' : '' }}" type="text" name="nom" id="nom" value="{{ old('nom', '') }}" required>
                @if($errors->has('nom'))
                    <span class="text-danger">{{ $errors->first('nom') }}</span>
                @endif
                <span class="help-block">{{ trans('') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="prenom">{{ trans('Prénom') }}</label>
                <input class="form-control {{ $errors->has('prenom') ? 'is-invalid' : '' }}" type="text" name="prenom" id="prenom" value="{{ old('prenom', '') }}" required>
                @if($errors->has('prenom'))
                    <span class="text-danger">{{ $errors->first('prenom') }}</span>
                @endif
                <span class="help-block">{{ trans('') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="date_naissance">{{ trans('Date de naissance') }}</label>
                <input class="form-control {{ $errors->has('date_naissance') ? 'is-invalid' : '' }}" type="date" name="date_naissance" id="date_naissance" value="{{ old('date_naissance', '') }}" required>
                @if($errors->has('date_naissance'))
                    <span class="text-danger">{{ $errors->first('date_naissance') }}</span>
                @endif
                <span class="help-block">{{ trans('') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="sexe">{{ trans('Sexe') }}</label>
                <label class="radio-inline {{ $errors->has('sexe') ? 'is-invalid' : '' }}"><input type="radio" name="sexe" value="masculin" checked>Masculin</label>
                <label class="radio-inline {{ $errors->has('sexe') ? 'is-invalid' : '' }}"><input type="radio" name="sexe" value="feminin">Féminin</label>
                @if($errors->has('sexe'))
                    <span class="text-danger">{{ $errors->first('sexe') }}</span>
                @endif
                <span class="help-block">{{ trans('') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="nationalite">{{ trans('Nationalité') }}</label>
                <input class="form-control {{ $errors->has('nationalite') ? 'is-invalid' : '' }}" type="text" name="nationalite" id="nationalite" value="{{ old('nationalite', '') }}" required>
                @if($errors->has('nationalite'))
                    <span class="text-danger">{{ $errors->first('nationalite') }}</span>
                @endif
                <span class="help-block"></span>
            </div>
            <div class="form-group">
                <label class="required" for="creches">{{ trans('creches') }}</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs select-all" style="border-radius: 0">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                </div>
                <select class="form-control select2 " name="creche_id" id="creche_id" multiple required>
                    @foreach($creches as $id => $creches)
                        <option value="{{ $id }}" {{ in_array($id, old('creches', [])) ? 'selected' : '' }}>{{ $creches }}</option>
                    @endforeach
                </select>
                @if($errors->has('creches'))
                    <span class="text-danger">{{ $errors->first('creches') }}</span>
                @endif
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>


    </div>
</div>
@endsection

Appcreche/resources/views/admin/bebes/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('bébé') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.bebes.update", [$bebe->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="nom">{{ trans('Nom ') }}</label>
                <input class="form-control {{ $errors->has('nom') ? 'is-invalid' : '' }}" type="text" name="nom" id="nom" value="{{ old('nom', $bebe->nom) }}" required>
                @if($errors->has('nom'))
                    <span class="text-danger">{{ $errors->first('nom') }}</span>
                @endif
                <span class="help-block">{{ trans('') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="prenom">{{ trans('Prénom') }}</label>
                <input class="form-control {{ $errors->has('prenom') ? 'is-invalid' : '' }}" type="text" name="prenom" id="prenom" value="{{ old('prenom', $bebe->prenom) }}" required>
                @if($errors->has('prenom'))
                    <span class="text-danger">{{ $errors->first('prenom') }}</span>
                @endif
                <span class="help-block">{{ trans('') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="date_naissance">{{ trans('Date de naissance') }}</label>
                <input class="form-control {{ $errors->has('date_naissance') ? 'is-invalid' : '' }}" type="date" name="date_naissance" id="date_naissance" value="{{ old('date_naissance', $bebe->date_naissance) }}" required>
                @if($errors->has('date_naissance'))
                    <span class="text-danger">{{ $errors->first('date_naissance') }}</span>
                @endif
                <span class="help-block">{{ trans('') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="sexe">{{ trans('Sexe') }}</label>
                <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <label class="form-check-label" for="sexe1" >
                <input class="form-check-input" class="form-control {{ $errors->has('sexe') ? 'is-invalid' : '' }}" type="radio" name="sexe" id="sexe1" value="masculin" {{ $bebe->sexe == 'masculin' ? 'checked' : '' }}> 
                Masculin
                </label>
                &nbsp; &nbsp; &nbsp; &nbsp;
                <label class="form-check-label" for="sExe2" >
                <input class="form-check-input" class="form-control {{ $errors->has('sexe') ? 'is-invalid' : '' }}" type="radio" name="sexe" id="sexe2" value="feminin" {{ $bebe->sexe == 'feminin' ? 'checked' : '' }}>
                Féminin
            </label>
            </div>
            <div class="form-group">
                <label class="required" for="nationalite">{{ trans('Nationalité') }}</label>
                <input class="form-control {{ $errors->has('nationalite') ? 'is-invalid' : '' }}" type="text" name="nationalite" id="nationalite" value="{{ old('nationalite', $bebe->nationalite) }}" required>
                @if($errors->has('nationalite'))
                    <span class="text-danger">{{ $errors->first('nationalite') }}</span>
                @endif
                <span class="help-block"></span>
            </div>
            <div class="form-group">
                <label class="required" for="creches">{{ trans('creches') }}</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs select-all" style="border-radius: 0">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                </div>
                <select class="form-control select2 " name="creche_id" id="creche_id" multiple required>
                    @foreach($creches as $id => $creches)
                        <option value="{{ $id }}" {{ in_array($id, old('creches', [])) ? 'selected' : '' }}>{{ $creches }}</option>
                    @endforeach
                </select>
                @if($errors->has('creches'))
                    <span class="text-danger">{{ $errors->first('creches') }}</span>
                @endif
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>


    </div>
</div>
@endsection

Appcreche/resources/views/admin/bebes/index.blade.php
@extends('layouts.admin')
@section('content')

    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.bebes.create") }}">
                {{ trans('global.add') }} {{ trans('bébé') }}
            </a>
        </div>
    </div>
<div class="card">
    <div class="card-header">
        {{ trans('bébé') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-bebe">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('id') }}
                        </th>
                        <th>
                            {{ trans('nom') }}
                        </th>
                        <th>
                            {{ trans('prenom') }}
                        </th>
                        <th>
                            {{ trans('date de naissance') }}
                        </th>
                        <th>
                            {{ trans('sexe') }}
                        </th>
                        <th>
                            {{ trans('nationalité') }}
                        </th>
                        <th>
                            {{ trans('Crèche') }}
                        </th>
                        <th>
                            
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($bebes as $key => $bebe)
                        <tr data-entry-id="{{ $bebe->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $bebe->id ?? '' }}
                            </td>
                            <td>
                                {{ $bebe->nom ?? '' }}
                            </td>
                            <td>
                                {{ $bebe->prenom ?? '' }}
                            </td>
                            <td>
                                {{ $bebe->date_naissance ?? '' }}
                            </td>
                            <td>
                                {{ $bebe->sexe ?? '' }}
                            </td>
                            <td>
                                {{ $bebe->nationalite ?? '' }}
                            </td>
                            <td>
                                <span class="badge badge-info">{{ $bebe->creche->nom ?? '' }}</span>
                            </td>
                            <td>
                                
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.informations_supplementaires.create', $bebe->id) }}">
                                        {{ trans('global.show') }}
                                    </a>
                              

                                
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.bebes.edit', $bebe->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                              

                                
                                    <form action="{{ route('admin.bebes.destroy', $bebe->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                              
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>


    </div>
</div>
@endsection

Appcreche/resources/views/admin/bebes/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('bébé') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.bebes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>

                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                <a href="{{ route('admin.informations_supplementaires.create') }}">
                    <i style="color:orange;" class="fas fa-plus-circle"></i>
                    
                    {{ trans('Ajouter des informations supplémentaires') }}
                </a>

            </div>
            <table class="" >
                <tbody >
                    <tr>
                        <th style="font-weight:normal;">
                            {{ trans('Id') }}
                        </th>
                        <td>
                            {{ $bebe->id }}
                        </td>
                    </tr>
                    <tr>
                        <th style="font-weight:normal;">
                            {{ trans('Situation familiale') }}
                        </th>
                        <td>
                            {{ $bebe->nom }}
                        </td>
                    </tr>
                    <tr>
                        <th style="font-weight:normal;">
                            {{ trans('Responsable légal(e)') }}
                        </th>
                        <td>
                            {{ $bebe->prenom }}
                        </td>
                    </tr>
                    <br>
                    <tr>
                        <th><br><i> Personne à prévenir en cas d'urgence</i></th>
                    </tr>     
                    <tr>      
                        <th style="font-weight:normal;">
                            {{ trans('Nom') }}
                        </th>
                        <td>
                            {{ $bebe->date_naissance }}
                        </td>
                    </tr>
                    <tr>
                        <th style="font-weight:normal;">
                            {{ trans('Prénom') }}
                        </th>
                        <td>
                            {{ $bebe->sexe }}
                        </td>
                    </tr>
                    <tr>
                        <th style="font-weight:normal;">
                            {{ trans('Téléphone') }}
                        </th>
                        <td>
                            {{ $bebe->nationalite }}
                        </td>
                    </tr>
                    <tr>
                        <th style="font-weight:normal;">
                            {{ trans('Lien') }}
                        </th>
                        <td>
                            <span class="badge badge-info">{{ $bebe->creche->nom }}</span>
                        </td>
                    </tr>
                    <tr>
                        <th style="font-weight:normal;">
                            {{ trans('CNI') }}
                        </th>
                        <td>
                            {{ $bebe->nationalite }}
                        </td>
                    </tr>
                    <tr>
                        <th><br><i> Pédiatre de l'enfant</i></th>
                    </tr>
                    <tr>
                        <th style="font-weight:normal;">
                            {{ trans('Nom') }}
                        </th>
                        <td>
                            {{ $bebe->nationalite }}
                        </td>
                    </tr>
                    <tr>
                        <th style="font-weight:normal;">
                            {{ trans('Prénom') }}
                        </th>
                        <td>
                            {{ $bebe->nationalite }}
                        </td>
                    </tr>
                    <tr>
                        <th style="font-weight:normal;">
                            {{ trans('Téléphone') }}
                        </th>
                        <td>
                            {{ $bebe->nationalite }}
                        </td>
                    </tr>
                    <tr>
                        <th><br><i> Personne autorisée à prendre l'enfant &nbsp;&nbsp;</i></th>
                    </tr>
                    <tr>
                        <th style="font-weight:normal;">
                            {{ trans('Nom') }}
                        </th>
                        <td>
                            {{ $bebe->nationalite }}
                        </td>
                    </tr>
                    <tr>
                        <th style="font-weight:normal;">
                            {{ trans('Prénom') }}
                        </th>
                        <td>
                            {{ $bebe->nationalite }}
                        </td>
                    </tr>
                    <tr>
                        <th style="font-weight:normal;">
                            {{ trans('Téléphone') }}
                        </th>
                        <td>
                            {{ $bebe->nationalite }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <br>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.bebes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>


    </div>
</div>
@endsection