Appcreche/routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Creches
    Route::delete('creches/destroy', 'CrechesController@massDestroy')->name('creches.massDestroy');
    Route::resource('creches', 'CrechesController');

    // Bebes
    Route::delete('bebes/destroy', 'BebesController@massDestroy')->name('bebes.massDestroy');
    Route::resource('bebes', 'BebesController');

    // Informations_supplementaires
    Route::delete('informations_supplementaires/destroy', 'Informations_supplementairesController@massDestroy')->name('informations_supplementaires.massDestroy');
    Route::resource('informations_supplementaires', 'Informations_supplementairesController');
});

Appcreche/app/Informations_Supplementaires.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Informations_Supplementaires extends Model
{
    protected $table = 'informations_supplementaires';
    public $timestamps = true;

    public function bebe()
    {
        return $this->belongsTo('Bebe');
    }
}

Appcreche/app/Http/Controllers/Admin/Informations_supplementairesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Informations_Supplementaires;

class Informations_supplementairesController extends Controller
{
    public function index()
    {
        
        $informations_supplementaires = Informations_supplementaires::all();

        return view('admin.informations_supplementaires.index', compact('informations_supplementaires'));
    }

    public function create()
    {

        $informations_supplementaires = Informations_supplementaires::all();

        return view('admin.informations_supplementaires.create', compact('informations_supplementaires'));
    }
}

Appcreche/resources/views/admin/informations_supplementaires/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('bébé') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.bebes.update", [$bebe->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="nom">{{ trans('Nom ') }}</label>
                <input class="form-control {{ $errors->has('nom') ? 'is-invalid' : '' }}" type="text" name="nom" id="nom" value="{{ old('nom', $bebe->nom) }}" required>
                @if($errors->has('nom'))
                    <span class="text-danger">{{ $errors->first('nom') }}</span>
                @endif
                <span class="help-block">{{ trans('') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="prenom">{{ trans('Prénom') }}</label>
                <input class="form-control {{ $errors->has('prenom') ? 'is-invalid' : '' }}" type="text" name="prenom" id="prenom" value="{{ old('prenom', $bebe->prenom) }}" required>
                @if($errors->has('prenom'))
                    <span class="text-danger">{{ $errors->first('prenom') }}</span>
                @endif
                <span class="help-block">{{ trans('') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="date_naissance">{{ trans('Date de naissance') }}</label>
                <input class="form-control {{ $errors->has('date_naissance') ? 'is-invalid' : '' }}" type="date" name="date_naissance" id="date_naissance" value="{{ old('date_naissance', $bebe->date_naissance) }}" required>
                @if($errors->has('date_naissance'))
                    <span class="text-danger">{{ $errors->first('date_naissance') }}</span>
                @endif
                <span class="help-block">{{ trans('') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="sexe">{{ trans('Sexe') }}</label>
                <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <label class="form-check-label" for="sexe1" >
                <input class="form-check-input" class="form-control {{ $errors->has('sexe') ? 'is-invalid' : '' }}" type="radio" name="sexe" id="sexe1" value="masculin" {{ $bebe->sexe == 'masculin' ? 'checked' : '' }}> 
                Masculin
                </label>
                &nbsp; &nbsp; &nbsp; &nbsp;
                <label class="form-check-label" for="sExe2" >
                <input class="form-check-input" class="form-control {{ $errors->has('sexe') ? 'is-invalid' : '' }}" type="radio" name="sexe" id="sexe2" value="feminin" {{ $bebe->sexe == 'feminin' ? 'checked' : '' }}>
                Féminin
            </label>
            </div>
            <div class="form-group">
                <label class="required" for="nationalite">{{ trans('Nationalité') }}</label>
                <input class="form-control {{ $errors->has('nationalite') ? 'is-invalid' : '' }}" type="text" name="nationalite" id="nationalite" value="{{ old('nationalite', $bebe->nationalite) }}" required>
                @if($errors->has('nationalite'))
                    <span class="text-danger">{{ $errors->first('nationalite') }}</span>
                @endif
                <span class="help-block"></span>
            </div>
            <div class="form-group">
                <label class="required" for="creches">{{ trans('creches') }}</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs select-all" style="border-radius: 0">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                </div>
                <select class="form-control select2 " name="creche_id" id="creche_id" multiple required>
                    @foreach($creches as $id => $creches)
                        <option value="{{ $id }}" {{ in_array($id, old('creches', [])) ? 'selected' : '' }}>{{ $creches }}</option>
                    @endforeach
                </select>
                @if($errors->has('creches'))
                    <span class="text-danger">{{ $errors->first('creches') }}</span>
                @endif
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>


    </div>
</div>
@endsection

Appcreche/resources/views/admin/informations_supplementaires/index.blade.php
@extends('layouts.admin')
@section('content')

    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.bebes.create") }}">
                {{ trans('global.add') }} {{ trans('bébé') }}
            </a>
        </div>
    </div>
<div class="card">
    <div class="card-header">
        {{ trans('bébé') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-bebe">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('id') }}
                        </th>
                        <th>
                            {{ trans('nom') }}
                        </th>
                        <th>
                            {{ trans('prenom') }}
                        </th>
                        <th>
                            {{ trans('date de naissance') }}
                        </th>
                        <th>
                            {{ trans('sexe') }}
                        </th>
                        <th>
                            {{ trans('nationalité') }}
                        </th>
                        <th>
                            {{ trans('Crèche') }}
                        </th>
                        <th>
                            
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($bebes as $key => $bebe)
                        <tr data-entry-id="{{ $bebe->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $bebe->id ?? '' }}
                            </td>
                            <td>
                                {{ $bebe->nom ?? '' }}
                            </td>
                            <td>
                                {{ $bebe->prenom ?? '' }}
                            </td>
                            <td>
                                {{ $bebe->date_naissance ?? '' }}
                            </td>
                            <td>
                                {{ $bebe->sexe ?? '' }}
                            </td>
                            <td>
                                {{ $bebe->nationalite ?? '' }}
                            </td>
                            <td>
                                <span class="badge badge-info">{{ $bebe->creche->nom ?? '' }}</span>
                            </td>
                            <td>
                                
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.bebes.show', $bebe->id) }}">
                                        {{ trans('Info Sup') }}
                                    </a>
                              

                                
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.bebes.edit', $bebe->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                              

                                
                                    <form action="{{ route('admin.bebes.destroy', $bebe->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                              
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>


    </div>
</div>
@endsection

Appcreche/resources/views/admin/informations_supplementaires/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('bébé') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.bebes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('Id') }}
                        </th>
                        <td>
                            {{ $bebe->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('Nom') }}
                        </th>
                        <td>
                            {{ $bebe->nom }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('Prénom') }}
                        </th>
                        <td>
                            {{ $bebe->prenom }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('Date de naissance') }}
                        </th>
                        <td>
                            {{ $bebe->date_naissance }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('Sexe') }}
                        </th>
                        <td>
                            {{ $bebe->sexe }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('Nationalité') }}
                        </th>
                        <td>
                            {{ $bebe->nationalite }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('Crèche') }}
                        </th>
                        <td>
                            <span class="badge badge-info">{{ $bebe->creche->nom }}</span>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.bebes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>


    </div>
</div>
@endsection